[tool.briefcase]
project_name = "Beeware Toga Test App"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/beeware_toga_test_app"
license = "MIT license"
author = 'Michał Bultrowicz'
author_email = "michał@example.com"

[tool.briefcase.app.beeware_toga_test_app]
formal_name = "Beeware Toga Test App"
description = "My first application"
icon = "src/beeware_toga_test_app/resources/beeware_toga_test_app"
sources = ['src/beeware_toga_test_app']
requires = []


[tool.briefcase.app.beeware_toga_test_app.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.beeware_toga_test_app.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.beeware_toga_test_app.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.beeware_toga_test_app.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.beeware_toga_test_app.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
