---
version: '3'

services:

  api:
    build:
      context: .
    image: sample_backend
    ports:
      - "${API_PORT:-8080}:8080"
    links:
      - database
    environment:
      - POSTGRES_HOST=database

  database:
    image: postgres:15.2
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    # defining a volume, so that the data is persistent between restarts
    volumes:
      - database-data:/var/lib/postgresql/data
    # The container logs will hold all SQL statements executed.
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

volumes:
  database-data:
