---
version: '3'

services:

  api:
    command: ["uvicorn", "--host", "0.0.0.0", "--port", "8080", "sample_backend.main:app", "--reload"]
    # Helps with development by mounting the code directly into the container.
    volumes:
      - ./sample_backend/:/app/sample_backend/
